export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://halsokostguiden.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/vitaminer","priority":"0.8","changefreq":"weekly"},{"path":"/kosttillskott","priority":"0.8","changefreq":"weekly"},{"path":"/vegansk","priority":"0.8","changefreq":"weekly"},{"path":"/sport","priority":"0.8","changefreq":"weekly"},{"path":"/online","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/halsasenior-vs-vitalplus","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsasenior-vs-seniorbalans","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsasenior-vs-halsokraft-60","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsasenior-vs-livskraft-senior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsasenior-vs-seniorhalsadirekt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsasenior-vs-aktivsenior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/vitalplus-vs-seniorbalans","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/vitalplus-vs-halsokraft-60","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/vitalplus-vs-livskraft-senior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/vitalplus-vs-seniorhalsadirekt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/vitalplus-vs-aktivsenior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/seniorbalans-vs-halsokraft-60","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/seniorbalans-vs-livskraft-senior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/seniorbalans-vs-seniorhalsadirekt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/seniorbalans-vs-aktivsenior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsokraft-60-vs-livskraft-senior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsokraft-60-vs-seniorhalsadirekt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/halsokraft-60-vs-aktivsenior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/livskraft-senior-vs-seniorhalsadirekt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/livskraft-senior-vs-aktivsenior","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/seniorhalsadirekt-vs-aktivsenior","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }